name: axon
type: laravel
docroot: public
php_version: "8.3"
webserver_type: nginx-fpm
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
database:
    type: mariadb
    version: "11.8"
use_dns_when_possible: true
composer_version: "2"
web_environment: []
nodejs_version: "22"
corepack_enable: false
web_extra_exposed_ports:
  - name: vite
    container_port: 5173
    http_port: 5174
    https_port: 5173